### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by danieljl** [tensorflow/model-analysis#17] opened 2018-08-27 07:53 UTC
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow Model Analysis)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13.6
-   **TensorFlow Model Analysis installed from (source or binary)**: binary
-   **TensorFlow Model Analysis version (use command below)**: 0.9.0
-   **Python version**: 2.7.14
-   **Jupyter Notebook version**: 1.0.0
-   **Exact command to reproduce**: Follow [Chicago Taxi Example (local example)](https://www.tensorflow.org/tfx/model_analysis/examples/chicago_taxi#run_the_local_example) tutorial.

### Describe the problem

I ran [Chicago Taxi Example notebook](https://github.com/tensorflow/model-analysis/blob/master/examples/chicago_taxi/chicago_taxi_tfma.ipynb) on Firefox and the TF Model Analysis interactive widget didn't show up. At first I thought there was a problem when I installed and enabled `tensorflow_model_analysis` Jupyter nbextension. It turned out when I opened the notebook in Chrome, it worked perfectly.

### Source code / logs

Firefox' console showed that `tfma_widget_js` is successfully loaded:
```
Use of Mutation Events is deprecated. Use MutationObserver instead. jquery.min.js:2
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later... menubar.js:277
accessing "actions" on the global IPython/Jupyter is not recommended. Pass it to your objects contructors at creation time main.js:208
Loaded moment locale en bidi.js:19
load_extensions 
Arguments { 0: "jupyter-js-widgets/extension", 1: "tfma_widget_js/extension", … }
utils.js:60
Loading extension: tfma_widget_js/extension utils.js:37
Session: kernel_created (fedc5d8c-5b4b-4b18-9029-685745010dd4) session.js:54
Starting WebSockets: ws://localhost:8888/api/kernels/fd4631da-a6de-4077-bc96-b52c0fa6a0e9 kernel.js:459
Loading extension: jupyter-js-widgets/extension utils.js:37
Kernel: kernel_connected (fd4631da-a6de-4077-bc96-b52c0fa6a0e9) kernel.js:103
Kernel: kernel_ready (fd4631da-a6de-4077-bc96-b52c0fa6a0e9) kernel.js:103 
```

Comparison to Chrome's console:
```
load_extensions Arguments(2) ["jupyter-js-widgets/extension", "tfma_widget_js/extension", callee: (...), Symbol(Symbol.iterator): ƒ]
bidi.js:19 Loaded moment locale en
session.js:54 Session: kernel_created (fedc5d8c-5b4b-4b18-9029-685745010dd4)
kernel.js:459 Starting WebSockets: ws://localhost:8888/api/kernels/fd4631da-a6de-4077-bc96-b52c0fa6a0e9
utils.js:37 Loading extension: tfma_widget_js/extension
kernel.js:103 Kernel: kernel_connected (fd4631da-a6de-4077-bc96-b52c0fa6a0e9)
kernel.js:103 Kernel: kernel_ready (fd4631da-a6de-4077-bc96-b52c0fa6a0e9)
utils.js:37 Loading extension: jupyter-js-widgets/extension
[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated. Please refer to https://goo.gl/EGXzpw for possible migration paths.
```

**Comment by pfyang** [comment] 2018-08-27 20:49
Hi Daniel,

For completeness, what version of FF are you using? (61?) Do you see any other JS errors in the browser console? Is vulcanized_template.html loaded?

The issue is likely caused by bad interactions between the version of polyfill / Polymer we use and newer FF. We will be updating the Polymer we use later this year and hopefully that will help resolve this issue. We will ping back this bug when that happens.

In the meantime, please continue to use Chrome for the visualization.

Thank you for trying out TFMA and reporting this!

**Comment by danieljl** [comment] 2018-08-28 04:55
>what version of FF are you using?

61.0.2

>Do you see any other JS errors in the browser console?

No

>Is vulcanized_template.html loaded?

No on Firefox

**Comment by harshini-gadige** [comment] 2018-10-23 22:46
@pfyang  -  Hi, any update on this ?

**Comment by pfyang** [comment] 2018-10-24 20:52
We have fixed an error when constructing the url for vulcanized_template.html. Please give it a try to see if that file loads and whether the UI works as expected.

If the file loads but the UI still not showing up, it is likely due to the polymer version we use. We will update it early next year.

**Comment by harshini-gadige** [comment] 2018-10-24 21:55
@danieljl -  Please try as mentioned above.

**Comment by harshini-gadige** [comment] 2018-11-16 21:02
> @danieljl - Please try as mentioned above.

@danieljl  -  We didn't receive any response on this. Please confirm if this is still an issue and if not, feel free to close this.

**Comment by hgadig** [comment] 2019-03-13 23:23
Closing this as there is no response received from the user.

**Closed by hgadig** 2019-03-13 23:23 UTC
Labels: stat:awaiting response, type:bug/performance
