### ISSUE TITLE
Support for regression models?

### ISSUE THREAD

**Issue by samithaj** [tensorflow/model-analysis#43] opened 2019-04-09 05:52 UTC
Is tfma support  regression models?? Like `tf.estimator.DNNLinearCombinedRegressor`

**Comment by loiccordone** [comment] 2019-04-16 08:51
Do you have any info on this? Are we missing something or is it not supported yet?

**Comment by chuanyu** [comment] 2019-04-16 18:01
Yes, all canned Estimators are supported. Did you run into problems trying to get a regression model to work?

**Comment by loiccordone** [comment] 2019-04-17 11:35
We have access only to average_loss, label/mean, post_export_metrics/example_count, prediction/mean. Can we have access to regression tf.metrics like mae, mse, rmse, mcd ?

**Comment by chuanyu** [comment] 2019-04-17 20:39
You can add metrics you want to the canned Estimators using [`tf.estimator.add_metrics`](https://www.tensorflow.org/api_docs/python/tf/contrib/estimator/add_metrics)

**Comment by loiccordone** [comment] 2019-04-17 20:45
It's exactly what I want, thanks! Sorry for the inconvenience.

**Comment by loiccordone** [comment] 2019-04-23 08:30
Hello, any updates on my edit? I can't find any info on the internet. Thanks!

**Comment by chuanyu** [comment] 2019-04-23 17:53
Sorry, GitHub doesn't send notifications for edits, so I didn't realise you had made an update.

The `predictions` argument is the same as the `predictions` dictionary in the `EstimatorSpec` returned by your `model_fn`. It looks like it's a dictionary containing a single key named `predictions`, so you probably want to do `mean_absolute_error(labels, predictions['predictions'])`.

**Comment by loiccordone** [comment] 2019-04-25 12:01
It works, thanks!

**Comment by gowtham-kp** [comment] 2019-05-07 16:52
Closing the issue due to the lack of recent activity. Please feel free to add additional information and open the issue again. Thanks!

**Closed by gowtham-kp** 2019-05-07 16:52 UTC
Labels: type:support
